#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #10
# Public test 2 (public02)
#
# Tests running the first program to compare two rectangles that have equal
# areas, although their four sides are all different.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog1.s < public02.inputdata | tail -n +2
