#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #10
# Public test 1 (public01)
#
# Tests running the first program to compare two rectangles whose four sides
# are all the same.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog1.s < public01.inputdata | tail -n +2
