#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #10
# Public test 7 (public07)
#
# Tests running the second program to compute the number of digits in the
# number 65535 in base 2.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog2.s < public07.inputdata | tail -n +2
