#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #10
# Public test 9 (public09)
#
# Tests running the second program to compute the number of digits in the
# number -23456 in base 10.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog2.s < public09.inputdata | tail -n +2
